<?php 
             function unset_session(){
                        if(!empty($_SESSION[take_detail])){
                        unset($_SESSION[take_detail]);}
                        if(!empty($_SESSION[take_date1])){
                        unset($_SESSION[take_date1]);}
                        if(!empty($_SESSION[take_date2])){
                        unset($_SESSION[take_date2]);}
                        if(!empty($_SESSION[check_date1])){
                        unset($_SESSION[check_date1]);}
                        if(!empty($_SESSION[take_name])){
                        unset($_SESSION[take_name]);}
                        if(!empty($_SESSION[category])){
                        unset($_SESSION[category]);}
                        if(!empty($_SESSION[place])){
                        unset($_SESSION[place]);}
                        if(!empty($_SESSION[set_dep])){
                        unset($_SESSION[set_dep]);}
                        if(!empty($_SESSION[checkdate])){
                        unset($_SESSION[checkdate]);}
                        if(!empty($_SESSION[check_date01])){
                        unset($_SESSION[check_date01]);}
                        if(!empty($_SESSION[check_date02])){
                        unset($_SESSION[check_date02]);}
                        if(!empty($_SESSION[searchChangeRisk])){
                        unset($_SESSION[searchChangeRisk]);}
                        if(!empty($_SESSION[Rmng_status])){
                        unset($_SESSION[Rmng_status]);}
                        if(!empty($_SESSION[Rtake_date1])){
                        unset($_SESSION[Rtake_date1]);}
                        if(!empty($_SESSION[Rtake_date2])){
                        unset($_SESSION[Rtake_date2]);}
                        if(!empty($_SESSION[Rlevel_risk])){
                        unset($_SESSION[Rlevel_risk]);}
                        if(!empty($_SESSION[Rtake_dep])){
                        unset($_SESSION[Rtake_dep]);}
                        if(!empty($_SESSION[Rcategory])){
                        unset($_SESSION[Rcategory]);}
                        if(!empty($_SESSION[Rsubcategory])){
                        unset($_SESSION[Rsubcategory]);}
                        if(!empty($_SESSION[Search_fname])){
                        unset($_SESSION[Search_fname]);}
                        if(!empty($_SESSION[Search_lname])){
                        unset($_SESSION[Search_lname]);}
                        if(!empty($_SESSION[Search_category])){
                        unset($_SESSION[Search_category]);}
                        if(!empty($_SESSION[Search_subcategory])){
                        unset($_SESSION[Search_subcategory]);}
                        if(!empty($_SESSION[Search_department])){
                        unset($_SESSION[Search_department]);}
                        if(!empty($_SESSION[Search_place])){
                        unset($_SESSION[Search_place]);}
                        if(!empty($_SESSION[report_dep])){
                        unset($_SESSION[report_dep]);}
                        if(!empty($_SESSION[dep_id_report])){
                        unset($_SESSION[dep_id_report]);}
                        if(!empty($_SESSION[move_status_report])){
                        unset($_SESSION[move_status_report]);}
                        if(!empty($_SESSION[take_date1_report])){
                        unset($_SESSION[take_date1_report]);}
                        if(!empty($_SESSION[take_date2_report])){
                        unset($_SESSION[take_date2_report]);}  
                        if(!empty($_SESSION[mng_status_report])){
                        unset($_SESSION[mng_status_report]);}
                        if(!empty($_SESSION[take_detail_reportdep])){
                        unset($_SESSION[take_detail_reportdep]);}
                        if(!empty($_SESSION[take_detail_dep])){
                        unset($_SESSION[take_detail_dep]);}
                        if(!empty($_SESSION[sub_risk])){
                        unset($_SESSION[sub_risk]);}
                        if(!empty($_SESSION[pct])){
                        unset($_SESSION[pct]);}
                        if(!empty($_SESSION[ic])){
                        unset($_SESSION[ic]);}
                        if(!empty($_SESSION[recycle])){
                        unset($_SESSION[recycle]);}
                                
             }?>